name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: . # Change this if your HTML files are in a folder (e.g., ./src)
          action: ${{ github.event.action }}
